### PR TITLE
HIP version of PENNANT, running on AMD GPU hardware

### PR DESCRIPTION
**Pull request by rwvo**

### CODE REVIEW

**Comment by jpietarilagraham** [comment]
We will need a GitHub Contributor License Agreement.

Charles,

Do you want to set this up or should Galen or I do it?

**Comment by cferenba** [comment]
> Do you want to set this up or should Galen or I do it?

Could you or Galen please set this up - I'm not familiar with how to do it.

**Comment by cferenba** [comment]
I've just looked this over and it looks reasonable to me.  @jpietarilagraham please let me know when the license agreement is set up and I will approve.

**Comment by rwvo** [comment]
I don't know what the process is for the Github Contributor License Agreement, but I was wondering if the license agreement text is available somewhere already, so that I can run it by our legal department.

**Comment by rwvo** [comment]
Ping: any updates on the Github Contributor License Agreement?

**Review by cferenba — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
